#!/bin/bash

RED="\e[1;31m"
HELP="\e[1;33m"
FIN="\e[0m"

armv7_rpi4 (){
echo
echo -e "${RED}Downloading${FIN} ..."
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi4-v7-stable.tar.xz
wget -cq --show-progress https://github.com/pyavitz/rootfs-tarballs/releases/download/xlrootfs/debian-buster-rootfs-armhf.tar.xz
echo -e "${RED}Done.${FIN}"
echo
echo -e "${RED}Extracting and setting up directory${FIN}."
tar xf rpi4-v7-stable.tar.xz
rm -f rpi4-v7-stable.tar.xz
mv rpi4-v7-stable rpi4
echo -e "${RED}Ready${FIN}."
}

armv8_rpi4 (){
echo
echo -e "${RED}Downloading${FIN} ..."
wget -cq --show-progress https://github.com/pyavitz/rpi-img-builder/releases/download/linux/rpi4-stable.tar.xz
wget -cq --show-progress https://github.com/pyavitz/rootfs-tarballs/releases/download/xlrootfs/debian-buster-rootfs-aarch64.tar.xz
echo -e "${RED}Done.${FIN}"
echo
echo -e "${RED}Extracting and setting up directory${FIN}."
tar xf rpi4-stable.tar.xz
rm -f rpi4-stable.tar.xz
mv rpi4-stable rpi4
echo -e "${RED}Ready${FIN}."
}

choose_arm (){
UD=userdata.txt

userdata () {
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md or run make config." 3 51
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo -e "${RED}$UD file found${FIN}."
else 
    userdata
fi

case `grep -Fx "devuser=1" "userdata.txt" >/dev/null; echo $?` in
  0)
    echo ""
    echo -e "${RED}Wrong userdata file${FIN}!"
    echo ""
    while [ true ] ; do
    read -t 2 -n 1
    if [ $? = 0 ] ; then
    exit ;
    else
    dialog --infobox "Please review the README.md or run make config." 3 51
    fi
    done
    ;;
esac
if `grep -Fx 'ARM="armv7"' "userdata.txt" >/dev/null;`
	then armv7_rpi4;
fi
if `grep -Fx 'ARM="armv8"' "userdata.txt" >/dev/null;`
	then armv8_rpi4;
fi
}

if [ $# -eq 0 ]
then
        echo -e "\e[0;31mMissing options!${FIN}"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

ECHO="false"

while getopts "4h" OPTION; do
        case $OPTION in

                4)
                        ECHO="rpi4"
                        ;;
                h)                       
                        echo "Helper, downloads a binary Linux package and XL rootfs tarball."
                        echo "Make sure to run 'make config' before 'make image'."
                        echo ""
                        echo -e "   make 2711        Raspberry Pi 4b"
                        echo ""
                        exit 0
                        ;;

        esac
done
if [ $ECHO = "rpi4" ]
then
        choose_arm;
fi
